apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-configmap
  namespace: default
  annotations:
    'strategy.spinnaker.io/versioned': 'false'
data:
  {{ (tpl (.Files.Glob "resources/*").AsConfig . ) | indent 2 }}
