apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ include "spring-helm-demo.fullname" . }}-ingress
  labels:
    {{- include "spring-helm-demo.labels" . | nindent 4 }}
spec:
  rules:
    - host: spring-helm-demo-host.com
      http:
        paths:
          - backend:
              service:
                name: {{ include "spring-helm-demo.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix